### @Patch('/:id')
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "mehmet@updated.com"
}

### @Delete('/:id')
DELETE http://localhost:3000/auth/2
Content-Type: application/json

{}

### @Get()
GET http://localhost:3000/auth?email=mehmet@mehmet.com
Accept: application/json

### @Get('/:id')
GET http://localhost:3000/auth/1
Accept: application/json

### @Post('/signup')

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}
###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
"email": "test@test.com",
"password": "test"
}

###
GET http://localhost:3000/auth/getCurrentUser
Accept: application/json

###
POST http://localhost:3000/auth/signout
Content-Type: application/json




